import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router";
import { escrowService } from "../services/escrow-service";
import { formatCurrency } from "../utils/format";
import { useAuthStore } from "../store/auth-store";
import { Button } from "../components/common/button";
import {
  IconShield,
  IconCheck,
  IconX,
} from "../components/common/icons";
import type { InvitePreviewResponse } from "../types/index";

export default function SellerAcceptPage() {
  // Works for both /escrow/:id/accept (legacy) and /invite/:token (new format)
  const { id: paramId, token: paramToken } = useParams();
  const token = paramToken || paramId;
  const navigate = useNavigate();

  const [preview, setPreview] = useState<InvitePreviewResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [accepting, setAccepting] = useState(false);
  const [accepted, setAccepted] = useState(false);

  useEffect(() => {
    if (!token) return;
    setLoading(true);
    escrowService
      .getInvitePreview(token)
      .then(setPreview)
      .catch((e) =>
        setError(e instanceof Error ? e.message : "Invalid or expired invite link"),
      )
      .finally(() => setLoading(false));
  }, [token]);

  async function handleAccept() {
    if (!token) return;
    setAccepting(true);
    try {
      const authResult = await escrowService.acceptInvite(token);

      // Magic link effect: store JWTs and user session
      useAuthStore.getState().loginWithResult(authResult);

      setAccepted(true);
      // Navigate to the specific escrow dashboard
      const escrowId = authResult.response.escrowId;
      setTimeout(() => navigate(escrowId ? `/escrow/${escrowId}/dashboard` : `/`), 1500);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to accept invite");
    } finally {
      setAccepting(false);
    }
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] animate-fade-in">
        <div className="w-12 h-12 border-4 border-gray-100 border-t-primary-500 rounded-full animate-spin mb-6 shadow-sm" />
        <p className="text-sm font-bold text-gray-500 tracking-widest uppercase">Fetching Details…</p>
      </div>
    );
  }

  if (error || !preview) {
    return (
      <div className="text-center py-20 animate-fade-in">
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-[1.5rem] bg-red-50 border-2 border-red-100 mb-6 drop-shadow-sm">
          <IconX className="w-10 h-10 text-red-500" />
        </div>
        <h2 className="text-2xl font-extrabold text-gray-900 tracking-tight mb-2">Access Denied</h2>
        <p className="text-base font-medium text-gray-500">{error || "Invite not found or expired."}</p>
        <Button variant="ghost" onClick={() => navigate("/")} className="mt-8 rounded-xl font-bold">
          Return to Dashboard
        </Button>
      </div>
    );
  }

  if (accepted) {
    return (
      <div className="text-center py-20 animate-fade-in flex flex-col items-center">
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-[2rem] bg-emerald-50 border-4 border-emerald-100 mb-6 shadow-sm">
          <IconCheck className="w-10 h-10 text-emerald-500" />
        </div>
        <h2 className="text-3xl font-extrabold text-gray-900 tracking-tight">Escrow Accepted!</h2>
        <p className="text-base font-medium text-gray-500 mt-2">Securing your vault and redirecting…</p>
      </div>
    );
  }

  const isBuyer = preview.invitedRole === "BUYER";
  const roleLabel = isBuyer ? "Buyer" : "Seller";
  const roleColor = isBuyer ? "bg-blue-50 text-blue-700 border-blue-200" : "bg-emerald-50 text-emerald-700 border-emerald-200";

  const deliveryLabels: Record<string, string> = {
    DIGITAL: "Digital Product",
    PHYSICAL: "Physical Shipment",
    SERVICE: "Service",
  };

  return (
    <div className="max-w-xl mx-auto py-12 px-4 animate-fade-in">
      {/* Header */}
      <div className="text-center mb-10">
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-[1.75rem] border-2 border-gray-100 bg-white shadow-sm mb-6 drop-shadow-sm">
          <IconShield className="w-10 h-10 text-primary-500" />
        </div>
        <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight leading-tight">
          You've been invited as a{" "}
          <span className={`inline-flex items-center px-3 py-1 pb-1.5 rounded-xl border-2 text-2xl font-black ${roleColor} mx-1 align-baseline`}>
            {roleLabel}
          </span>
        </h1>
        <p className="text-base font-medium text-gray-500 mt-4 leading-relaxed max-w-sm mx-auto">
          Please review this escrow agreement generated by <span className="font-bold text-gray-900">{preview.createdByName}</span> before accepting.
        </p>
      </div>

      {/* Agreement Card */}
      <div className="bg-gray-900 text-white rounded-[2rem] shadow-2xl p-8 relative overflow-hidden mb-8 border border-gray-800">
        <div className="absolute top-0 inset-x-0 h-2 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScxMicgaGVpZ2h0PScxMic+PHBhdGggZD0nTTYuMDAyLTEuMDk3TDExLjgxNyA0LjkydjZMLjE5IDQuOTJ6JyBmaWxsPSdibGFjaycgZmlsbC1ydWxlPSdldmVub2RkJy8+PC9zdmc+')] bg-repeat-x opacity-10 block" />
        
        <p className="text-xs font-extrabold text-gray-400 uppercase tracking-widest mb-6">
          Agreement Terms
        </p>

        <div className="space-y-6">
          <div>
            <p className="text-xs font-bold text-gray-500 uppercase tracking-widest">Title</p>
            <p className="text-lg font-bold text-white tracking-tight mt-1">{preview.title}</p>
          </div>

          <div>
             <p className="text-xs font-bold text-gray-500 uppercase tracking-widest">
               {isBuyer ? "Amount to fund" : "Amount you'll receive"}
             </p>
             <p className="text-4xl font-black text-white tracking-tight mt-2">
               {formatCurrency(preview.amount, preview.currency)}
             </p>
          </div>

          <div className="pt-4 border-t border-gray-800">
            <p className="text-xs font-bold text-gray-500 uppercase tracking-widest">Description</p>
            <p className="text-sm font-medium text-gray-300 mt-2 leading-relaxed">
               {preview.description}
            </p>
          </div>

          <div className="pt-4 border-t border-gray-800">
            <p className="text-xs font-bold text-gray-500 uppercase tracking-widest">Delivery mode</p>
            <p className="text-sm font-bold text-white mt-1">
              {deliveryLabels[preview.deliveryType] || preview.deliveryType}
            </p>
          </div>
        </div>

        {/* Role-specific context */}
        <div className={`mt-8 rounded-[1.5rem] border-2 p-5 ${isBuyer ? "bg-blue-500/10 border-blue-500/20 text-blue-200" : "bg-emerald-500/10 border-emerald-500/20 text-emerald-200"}`}>
            <p className="text-sm font-bold leading-relaxed">
              {isBuyer
                ? "💡 As the buyer, you will be prompted to securely fund this escrow via Interswitch upon accepting. Funds are held safely until you confirm receipt of the delivery."
                : "💡 As the seller, you will fulfill the order outlined above. Funds will be released to your linked bank account immediately after the buyer confirms receipt."}
            </p>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-col gap-4">
        <Button
          className="w-full h-16 rounded-[1.25rem] text-lg font-extrabold tracking-wide drop-shadow-sm transition-transform active:scale-[0.98]"
          onClick={handleAccept}
          disabled={accepting}
        >
          {accepting ? "Accepting Agreement…" : `Accept Agreement as ${roleLabel}`}
        </Button>
        <Button
          variant="outline"
          className="w-full h-14 rounded-[1.25rem] text-base font-bold text-gray-500 border-2 border-gray-200 hover:border-gray-300 hover:text-gray-900 hover:bg-white transition-all"
          onClick={() => navigate("/")}
        >
          Decline & Return to Dashboard
        </Button>
      </div>

      {/* Security Footer */}
      <div className="mt-10 text-center">
        <div className="flex items-center justify-center gap-2 text-xs font-extrabold text-gray-300 uppercase tracking-widest">
          <IconShield className="w-4 h-4 opacity-50" />
          <span>Secured globally via Interswitch</span>
        </div>
      </div>
    </div>
  );
}
